NameCollectionTool/Models/HomeViewModel.cs
using NameCollectionTool.Dtos;

namespace NameCollectionTool.Models
{
    public class HomeViewModel
    {
        public List<PersonNameDto> PersonNames { get; set; }
        public List<PlaceNameDto> PlaceNames { get; set; }
        public List<TitleNameDto> TitleNames { get; set; }
        public List<SpellNameDto> SpellNames { get; set; }
        public List<ArtefactNameDto> ArtefactNames { get; set; }
        public List<OtherNameDto> OtherNames { get; set; }

    }
}

NameCollectionTool/Controllers/HomeController.cs
using LiteDB;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using NameCollectionTool.Dtos;
using NameCollectionTool.Models;
using NameCollectionTool.Services.Interfaces;
using System.Diagnostics;

namespace NameCollectionTool.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IPersonNameService _personNameService;
        private readonly IPlaceNamesService _placeNameService;

        public HomeController(ILogger<HomeController> logger, IConfiguration iConfig, IPersonNameService personNameService, IPlaceNamesService placeNameService)
        {
            _logger = logger;
            _personNameService = personNameService;
            _placeNameService = placeNameService;
        }

        public IActionResult Index()
        {
            HomeViewModel model = new HomeViewModel();

            model.PersonNames = _personNameService.GetAllPersonNames();
            model.PlaceNames = _placeNameService.GetAllNames();

            return View(model);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public IActionResult CultureManagement(string culture, string returnUrl)
        {
            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) }
            );

            return LocalRedirect(returnUrl);
        }
    }
}

NameCollectionTool/Controllers/PersonNamesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using NameCollectionTool.Dtos;
using NameCollectionTool.Models;
using NameCollectionTool.Services.Interfaces;

namespace NameCollectionTool.Controllers
{
    public class PersonNamesController : Controller
    {
        private readonly IPersonNameService _nameService;

        public PersonNamesController(IPersonNameService nameService)
        {
            _nameService = nameService;
        }

        public IActionResult Index()
        {
            return View();
        }

        // GET: PersonNames/Create
        public IActionResult Create(bool executedCreate = false)
        {
            if (executedCreate)
            {
                ViewBag.toast = "Name added to the collection!";
            }
            
            return View();
        }

        // POST: PersonNames/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind("FirstName,LastName,Gender,Etymology,Tags")] PersonNameViewModel name)
        {
            _nameService.InsertNewName(name);

            return RedirectToAction("Create",new { executedCreate = true });
        }

        public ActionResult Delete(int id, bool? saveChangesError = false)
        {
            _nameService.DeleteName(id);
            return RedirectToAction("Index", "Home");
        }
    }
}

NameCollectionTool/Controllers/PlaceNamesController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using NameCollectionTool.Dtos;
using NameCollectionTool.Models;
using NameCollectionTool.Services.Interfaces;

namespace NameCollectionTool.Controllers
{
    public class PlaceNamesController : Controller
    {
        private readonly IPlaceNamesService _nameService;

        public PlaceNamesController(IPlaceNamesService nameService)
        {
            _nameService = nameService;
        }

        public IActionResult Index()
        {
            return View();
        }

        // GET: PersonNames/Create
        public IActionResult Create(bool executedCreate = false)
        {
            if (executedCreate)
            {
                ViewBag.toast = "Name added to the collection!";
            }
            
            return View();
        }

        // POST: PersonNames/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind("Name,Tags")] PlaceNameViewModel placeName)
        {
            _nameService.InsertNewName(placeName);

            return RedirectToAction("Create",new { executedCreate = true });
        }

        public ActionResult Delete(int id, bool? saveChangesError = false)
        {
            _nameService.DeleteName(id);
            return RedirectToAction("Index", "Home");
        }
    }
}

NameCollectionTool/Views/Home/Index.cshtml
@model HomeViewModel

@{
    ViewData["Title"] = "Home";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
</div>

@*Person names table*@
 <div class="card mb-4">
     <div class="card-header">
         <div class="container-fluid">
            <div class="row">
                <div class="col-sm-10">
                    <i class="fa-solid fa-people-group"></i>
                    Person names
                </div>
                <div class="col-sm-2" style="text-align:right;">
                    <a asp-controller="PersonNames" asp-action="Create" style="color: green" data-toggle="tooltip" data-placement="top" title="Add a new name to the collection."><i class="fa-solid fa-square-plus"></i></a>
                </div>
            </div>
         </div>
     </div>
     <div class="card-body">
         <table class="datatable-table table table-striped" id="table">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col"><i class="fa-solid fa-toolbox"></i></th>
                    <th scope="col">Firstname</th>
                    <th scope="col">Lastname</th>
                    <th scope="col">Gender</th>
                    <th scope="col">Etymology</th>
                    <th scope="col">Tags</th>
                </tr>
            </thead>
            <tbody>
            @foreach (var name in Model.PersonNames)
            {
                <tr>
                    <th scope="row">@name.Id</th>
                    <td><a asp-controller="PersonNames" asp-action="Delete" asp-route-id="@name.Id" style="color: #ff6962" data-toggle="tooltip" data-placement="top" title="Remove this name from the collection."><i class="fa-solid fa-trash"></i></a></td>
                    <td>@name.FirstName</td>
                    <td>@name.LastName</td>
                    <td>@name.Gender</td>
                    <td>
                        @if (!string.IsNullOrEmpty(name.Etymology))
                            {
                                <a href="@name.Etymology" target="_blank">Link</a>
                            }
                    </td>
                    <td>
                    @if (name.Tags != null)
                    {  
                        @for (int i = 0; i < name.Tags.Count(); i++)
                                {
                                    if (i+1 < name.Tags.Count())
                                    {
                                        <span> @name.Tags[i] ,</span>
                                    }
                                    else
                                    {
                                        <span> @name.Tags[i]</span>
                                    }
                                }
                    }
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>


@*Place names table*@
 <div class="card mb-4">
     <div class="card-header">
         <div class="container-fluid">
            <div class="row">
                <div class="col-sm-10">
                    <i class="fa-solid fa-map-location-dot"></i>
                    Place names
                </div>
                <div class="col-sm-2" style="text-align:right;">
                    <a asp-controller="PlaceNames" asp-action="Create">Add name</a>
                </div>
            </div>
         </div>
     </div>
     <div class="card-body">
         <table class="datatable-table table table-striped" id="table">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col"><i class="fa-solid fa-toolbox"></i></th>
                    <th scope="col">Name</th>
                    <th scope="col">Tags</th>
                </tr>
            </thead>
            <tbody>
            @foreach (var name in Model.PlaceNames)
            {
                <tr>
                    <th scope="row">@name.Id</th>
                    <td><a asp-controller="PlaceNames" asp-action="Delete" asp-route-id="@name.Id" style="color: #ff6962"><i class="fa-solid fa-trash"></i></a></td>
                    <td>@name.Name</td>
                    <td>
                    @if (name.Tags != null)
                    {  
                        @for (int i = 0; i < name.Tags.Count(); i++)
                                {
                                    if (i+1 < name.Tags.Count())
                                    {
                                        <span> @name.Tags[i] ,</span>
                                    }
                                    else
                                    {
                                        <span> @name.Tags[i]</span>
                                    }
                                }
                    }
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>

@*Title names table*@
 <div class="card mb-4">
     <div class="card-header">
         <div class="container-fluid">
            <div class="row">
                <div class="col-sm-10">
                    <i class="fa-solid fa-crown"></i>
                    Title names
                </div>
                <div class="col-sm-2" style="text-align:right;">
                    <a asp-controller="PersonNames" asp-action="Create">Add name</a>
                </div>
            </div>
         </div>
     </div>
     <div class="card-body">
    </div>
</div>

@*Spell names table*@
 <div class="card mb-4">
     <div class="card-header">
         <div class="container-fluid">
            <div class="row">
                <div class="col-sm-10">
                    <i class="fa-solid fa-hand-sparkles"></i>
                    Spell names
                </div>
                <div class="col-sm-2" style="text-align:right;">
                    <a asp-controller="PersonNames" asp-action="Create">Add name</a>
                </div>
            </div>
         </div>
     </div>
     <div class="card-body">
    </div>
</div>

@*Artefact names table*@
 <div class="card mb-4">
     <div class="card-header">
         <div class="container-fluid">
            <div class="row">
                <div class="col-sm-10">
                    <i class="fa-solid fa-gem"></i>
                    Artefact names
                </div>
                <div class="col-sm-2" style="text-align:right;">
                    <a asp-controller="PersonNames" asp-action="Create">Add name</a>
                </div>
            </div>
         </div>
     </div>
     <div class="card-body">
    </div>
</div>



@section scripts {
     <script>
        // Enable datatables
        $(document).ready( function () {
            $('.datatable-table').DataTable();
            $('[data-toggle="tooltip"]').tooltip();
        } );
    </script>
}